# Generated by Django 4.0.6 on 2022-10-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='SOME STRING', max_length=120)),
                ('details', models.CharField(default='N/A', max_length=240)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
