# Generated by Django 4.0.6 on 2022-10-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='picture',
        ),
    ]
