# Generated by Django 4.0.6 on 2022-10-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.CharField(max_length=240),
        ),
    ]
