# Generated by Django 4.0.6 on 2022-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_address_alter_report_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.FileField(default='settings.MEDIA_ROOT/other-icon.png', upload_to=''),
        ),
    ]
