# Generated by Django 4.0.6 on 2022-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.FileField(default='media/other-icon.png', upload_to=''),
        ),
    ]
