# Generated by Django 4.0.6 on 2022-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_first_name_report_last_name_report_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
