# Generated by Django 4.0.6 on 2023-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_lat_report_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
