# Generated by Django 4.0.6 on 2023-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
