# Generated by Django 4.0.6 on 2023-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_lat_alter_report_lon_alter_report_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
