# Generated by Django 4.0.6 on 2022-09-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_category_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(default='SOME STRING', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.category'),
        ),
    ]
