# Generated by Django 4.0.6 on 2022-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_category_link_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='submit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
