# Generated by Django 4.0.6 on 2022-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_category_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
