# Generated by Django 4.0.6 on 2022-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_category_submit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='link',
            new_name='url',
        ),
    ]
